package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.UserEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.context.annotation.Bean;

import java.util.List;

@Mapper
public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated Wed Jul 01 10:36:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated Wed Jul 01 10:36:15 CST 2020
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated Wed Jul 01 10:36:15 CST 2020
     */
    UserEntity selectByPrimaryKey(Integer id);

    UserEntity selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated Wed Jul 01 10:36:15 CST 2020
     */
    List<UserEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated Wed Jul 01 10:36:15 CST 2020
     */
    int updateByPrimaryKey(UserEntity record);
}