package com.xiagao.dao.mapper;

import com.xiagao.model.pojo.mybatis.UserM;
import java.util.List;

public interface UserMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated
     */
    int insert(UserM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated
     */
    UserM selectByPrimaryKey(Integer id);

    UserM selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated
     */
    List<UserM> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_m
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserM record);
}
